language: go
dist: focal

go:
- 1.13.x

branches:
  only:
    - master

before_script:
  - go version
  - go get -u golang.org/x/lint/golint
  - GOLINT=`go list -f {{.Target}} golang.org/x/lint/golint`
  - PATH=$PATH:$GOLINT
  - GOPATH=$GOPATH:`pwd`

script:
  - make check
  - make test

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"
